In [2]:
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Option 1
from sklearn.datasets import load_iris

df=pd.DataFrame(load_iris().data,columns=load_iris().feature_names)
df['species']=load_iris().target


In [4]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [6]:
#Option 2 to load dataset
from sklearn.datasets import load_iris
x= pd.DataFrame(load_iris().data,columns=load_iris().feature_names)
y=pd.Series(load_iris().target)
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=20,stratify=y)

In [8]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
42                 4.4               3.2                1.3               0.2
16                 5.4               3.9                1.3               0.4
49                 5.0               3.3                1.4               0.2
94                 5.6               2.7                4.2               1.3
41                 4.5               2.3                1.3               0.3
..                 ...               ...                ...               ...
99                 5.7               2.8                4.1               1.3
30                 4.8               3.1                1.6               0.2
2                  4.7               3.2                1.3               0.2
130                7.4               2.8                6.1               1.9
75                 6.6               3.0                4.4               1.4

[105 rows x 4 columns]

In [9]:
y_train

42     0
16     0
49     0
94     1
41     0
      ..
99     1
30     0
2      0
130    2
75     1
Length: 105, dtype: int32

# Model Training

In [10]:
dt_clf= DecisionTreeClassifier()
dt_clf.fit(x_train,y_train)

DecisionTreeClassifier()

# Model Evaluation

In [11]:
# Test Data Accuracy

y_pred= dt_clf.predict(x_test)
print(y_pred[5:10])

cnf_matrix= confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cnf_matrix)
print("*"*50)

Acc_score= accuracy_score(y_test,y_pred)
print("Accuracy Score is:",Acc_score)
print("*"*50)

clf_report= classification_report(y_test,y_pred)
print("Classification Report:\n",clf_report)

[0 2 2 2 0]
Confusion Matrix:
 [[15  0  0]
 [ 0 14  1]
 [ 0  0 15]]
**************************************************
Accuracy Score is: 0.9777777777777777
**************************************************
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [12]:
# Train Data Accuracy

y_pred_train= dt_clf.predict(x_train)
print(y_pred_train[5:10])

cnf_matrix= confusion_matrix(y_train,y_pred_train)
print("Confusion Matrix:\n",cnf_matrix)
print("*"*50)

Acc_score= accuracy_score(y_train,y_pred_train)
print("Accuracy Score is:",Acc_score)
print("*"*50)

clf_report= classification_report(y_train,y_pred_train)
print("Classification Report:\n",clf_report)


[1 0 0 1 1]
Confusion Matrix:
 [[35  0  0]
 [ 0 35  0]
 [ 0  0 35]]
**************************************************
Accuracy Score is: 1.0
**************************************************
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        35

    accuracy                           1.00       105
   macro avg       1.00      1.00      1.00       105
weighted avg       1.00      1.00      1.00       105



In [13]:
plt.figure(figsize=(200,160))
plot_tree(dt_clf,feature_names=x.columns,class_names=['0','1','2'],filled=True)
plt.savefig('DecisionTree.pdf')